### PR TITLE
re-enable syntax highlighting after cycling the buffer

### PR DESCRIPTION
**Pull request by sontek**

### CODE REVIEW

**Comment by fholgado** [comment]
Hi Sontek,

If you look at the development branch, I fixed the dupe level check issue in a similar fashion. I will apply the other bug fix manually onto the development codebase that way you don't have to submit another pull request. Let me know what you think!

**Comment by sontek** [comment]
Perfect! :)

**Comment by fholgado** [comment]
Whoo hoo!

**Comment by neezer** [comment]
Should this be fixed now? I'm running the latest off master and I'm still having this issue... syntax highlighting is turned off when arriving at the last open buffer.
1. Open new buffer with HTML
2. Open new buffer with PHP
3. Close buffer with PHP
4. Returned to original buffer with HTML, with syntax highlighting disabled.

**Comment by fholgado** [comment]
Hey there! I haven't updated the main branch to the latest codebase. Try pulling from the development branch that should have this bug fixed.

**Comment by neezer** [comment]
Ahh, cool. I'll give that a try. Thanks!

**Pull request closed without merging**
