### PR TITLE
fix for &winminheight setting

### PR DESCRIPTION
**Pull request by zhaocai**

### CODE REVIEW

**Comment by weynhamz** [comment]
Can you give more details about this PR, why it is necessary?

**Comment by zhaocai** [comment]
if I set `winminheight` = 5, then `resize 1` will be size 5.

http://zhaocai.github.io/GoldenView.Vim/

**Comment by weynhamz** [comment]
Great, I get it, it wil be merged soon.

**Comment by weynhamz** [comment]
Merged in develop branch.

**Pull request closed without merging**
