### PR TITLE
MBE now ignores buffers with empty name

### PR DESCRIPTION
**Pull request by folke**
This fixes issue #3

### CODE REVIEW

**Comment by folke** [comment]
Maybe a little additional information :-)

I had the problem as listed in issue #3. After some investigation, I found the issue to be that the first time that FuzzyFinder shows its dropdown thingy, it first creates a "scratch" buffer with an empty name and then changes the name to "[fuf]". When the scratch buffer is created (and before the rename), the `AutoUpdate` on MBE is triggered through the autocmds. By ignoring buffers with no name, there is no focus stealing involved anymore.

Not sure if this affects other uses of MBE. I personally always do `:e FILENAME` for creating a new file, but maybe other create empty buffers that now no longer will appear in MBE?

**Comment by folke** [comment]
This apparently also fixes the session plugin :-) That one now happily asks me to resume an existing session.

**Comment by fholgado** [comment]
Hey Folke! Thank you so much for looking at this. I will take a look and let you know my findings.

**Comment by weynhamz** [comment]
Hey, guys

I have continued the developement of MBE for a while, a bunch of PRs have been merged into the develop branch of my fork of MBE at techlivezheng/vim-plugin-minibufexpl. 

The real issue is not about the empty buffer name, I think it is mainly because MBE steal the focus for a little bit while entering a buffer, after returning to the buffer, the 'wincmd p' would be pointed to MBE window. I believe that techlivezheng/vim-plugin-minibufexpl@3add236 and techlivezheng/vim-plugin-minibufexpl@4155048 should fix this issue now.  I also allowed the buffers with no name to be shown in MBE(techlivezheng/vim-plugin-minibufexpl@8fad45b) which seems good as now.

Please give it a try and let me know if it works.

**Pull request merged**
