### PR TITLE
Bad buffer state on startup caused by call to bufname() instead of bufnr()

### PR DESCRIPTION
**Pull request by doublemarked**
My initial unmodified buffer was always flagged red despite not being modified.

### CODE REVIEW

**Comment by weynhamz** [comment]
You do find where the problem lies, but the fix you give is not the right way. The third argument of the function `StartExplorer(sticky,delBufNum,currBufName)` is the current bufname, but the condition check happeed before appending '!' sign treats `currBufName` as a buf number where the real bebug lies, convert the `l:i` to buffer name is the simplest way to fix it, otherwise, we need to change lots of functions' definition.

**Comment by weynhamz** [comment]
Hey, I have merged a bunch of PRs into [my fork of MiniBufExpl](https://github.com/techlivezheng/vim-plugin-minibufexpl) which might intertests you. Due to the inactivity of this repo, it is might be the time for a tempary switch until @fholgado gets some time to refocus on this project.

**Comment by doublemarked** [comment]
Hey :)

I agree with you that the argument is named `currBufName` so it should behave a string, not a number. I wanted to minimize my changes, and only sought to make all `StartExplorer` calls consistent by changing the one discrepancy.

The direction of your patch makes sense, but you have not fixed all the calls to `StartExplorer`. In your file there are now two cases of it being called with `bufname("%")` as an argument but another three calls still passing `bufnr("%")`. I think you need to fix all calls to `StartExplorer`?

These comments are based on a fairly hasty code review, so feel free to correct me if I've overlooked something.

-Heath

**Comment by weynhamz** [comment]
Hey

At first, I do think the value passed to the `StartExplorer` should be the same type as the argument `currBufName` defined. But after I got much familiar with the code, I started to realize that the approach you took should be the right way. There are several palces in the code that `bufname('%')` and `bufnr('%')` are mixed, the right name for argument 'currBufName' of `StartExplorer`  should be `currBufNum`, so here came techlivezheng/vim-plugin-minibufexpl@dd2124d in which I fixed almost every place. Unfortunately, there was still one fish escaped, that's why techlivezheng/vim-plugin-minibufexpl@b2c692e came up. Everything should be good now.

All these commits are in the develop branch of my fork - techlivezheng/vim-plugin-minibufexpl@develop - along with a bunch of improving and refactoring commits, please take a look.

Cheers

**Comment by doublemarked** [comment]
Looks good now, I think!

**Comment by weynhamz** [comment]
Hey, I am closing this PR, because it has been merged into [the develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) and will soon be avaliable in @fholgado's repo in the coming relase 6.5.

**Comment by mikehaertl** [comment]
@doublemarked
Unfortunately this fix now introduced another bug for me: If i have 2 split windows, none of them is marked active anymore. See techlivezheng/vim-plugin-minibufexpl#4. @techlivezheng also seems to have stopped development on his version. As i don't know much about vimscript, maybe someone else can help out?

**Comment by doublemarked** [comment]
Hmm, sorry to hear this! I can look into it in the coming days and see if I can fix it.

**Comment by mikehaertl** [comment]
That would be awesome, thanks. Maybe also check the other ticket where i posted a link to my exact configuration in case you want to reproduce the issue.

**Pull request closed without merging**
