### PR TITLE
Workarounds for problems in current master

### PR DESCRIPTION
**Pull request by ssokolow**
This pull request covers all of the changes I've mentioned making so far.

I'd split them up, but I'm still getting the hang of GitHub's pull request system.

### CODE REVIEW

**Comment by fholgado** [comment]
Steven,

Just letting you know I'll be working on MBE this weekend and I will get this merged in. School + Hockey has started so I've got to get back in the rhythm of things :)

**Comment by fholgado** [comment]
Steven,

I've merged the changes into the latest development build. I've still got some more issues to fix, but this gets us a step closer. Thanks again for your help!

https://github.com/fholgado/minibufexpl.vim/tree/6.4.1b3

**Comment by ssokolow** [comment]
How exactly did you merge my commits? They don't appear to be merged using the normal Git merge mechanism and part of the reason I fork and merge even for trivial changes is because people often get my name wrong. (It's "Stephan", not "Steven" ...though usually it's the last name people get wrong.)

**Comment by fholgado** [comment]
Stephan,

I am so sorry for mixing up your name! At least I'm glad to hear I am not the only one :P I did the merges manually instead of using Git Merge since I was fixing other bugs before I did the merge and then realized that when you had cleaned up the trailing whitespace, it affected almost every line in the plugin which caused Git to create a conflict.

I will be sure to clean up the trailing whitespace in my next commit, but I think the changes were trivial enough that I have them in the right spot. Just let me know if you see anything out of the ordinary.

Thanks again,
Federico

**Comment by ssokolow** [comment]
Ahh, yeah. I committed that change to mine because I didn't expect to be making any other changes any time soon.

If you'd like to experiment with reworking my autocommand for stripping trailing whitespace into a manually-triggered command, it's at line 368 in https://github.com/ssokolow/profile/blob/master/.vimrc

**Pull request closed without merging**
